name: c_analysis
description: MR Crypto Analysis client app
version: 0.1.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  redux_logging: ^0.3.0
  json_serializable: ^2.0.2
  sass_builder: ^2.1.2
  rxdart: ^0.21.0
  chartjs: ^0.5.1

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
